export type Class =
  | 'Barbarian'
  | 'Cleric'
  | 'Druid'
  | 'Fighter'
  | 'Monk'
  | 'Paladin'
  | 'Ranger'
  | 'Rogue'
  | 'Sorcerer'
  | 'Votive'
  | 'Wizard'
  | 'Automaton'
  | 'Dragon'
  | 'Dryad'
  | 'Harpy'
  | 'Incarnation'
  | 'Naiad'
  | 'Oozeborn'
  | 'Treant'
  | 'Troll'
  | 'Vampire';

export type ClassArchetype =
  | 'Blank'
  // Barbarian
  | 'BattleforgedResilience'
  | 'Battlerager'
  | 'OutlandSavage'
  | 'PrimalWarrior'
  | 'Totemist'
  // Cleric
  | 'ClericDivineMagic'
  | 'DivineSpellMastery'
  | 'DomainInfluence'
  | 'Healer'
  | 'Preacher'
  // Druid
  | 'Elementalist'
  | 'NatureMagic'
  | 'NatureSpellMastery'
  | 'Shifter'
  | 'Wildspeaker'
  // Fighter
  | 'CombatDiscipline'
  | 'EquipmentTraining'
  | 'MartialMastery'
  | 'Sentinel'
  | 'Tactician'
  // Monk
  | 'Airdancer'
  | 'EsotericWarrior'
  | 'Ki'
  | 'PerfectedForm'
  | 'TranscendentSage'
  // Paladin
  | 'DevotedParagon'
  | 'PaladinDivineMagic'
  | 'DivineSpellExpertise'
  | 'StalwartGuardian'
  | 'ZealousWarrior'
  // Ranger
  | 'Beastmaster'
  | 'BoundaryWarden'
  | 'Huntmaster'
  | 'Scout'
  | 'WildernessWarrior'
  // Rogue
  | 'Assassin'
  | 'BardicMusic'
  | 'CombatTrickster'
  | 'JackOfAllTrades'
  | 'SuaveScoundrel'
  // Sorcerer
  | 'SorcererArcaneMagic'
  | 'SorcererArcaneSpellMastery'
  | 'DraconicMagic'
  | 'InnateArcanist'
  | 'WildMagic'
  // Votive
  | 'CovenantKeeper'
  | 'PactMagic'
  | 'PactSpellMastery'
  | 'PactboundWarrior'
  | 'Soulforged'
  // Wizard
  | 'Alchemist'
  | 'WizardArcaneMagic'
  | 'WizardArcaneSpellMastery'
  | 'ArcaneScholar'
  | 'SchoolSpecialist'
  // Uncommon species
  | 'Automaton'
  | 'Dragon'
  | 'Dryad'
  | 'Harpy'
  | 'Incarnation'
  | 'Naiad'
  | 'Oozeborn'
  | 'Treant'
  | 'Troll'
  | 'Vampire';

export interface RankAbility {
  complexity: number;
  description: string;
  isMagical: boolean;
  rank: number;
  name: string;
}
