// AUTO-GENERATED by monster_ui. Do not edit manually.
// Source: Rise/typescript/monster_ui/monsters_from_ui.json

import { Grimoire } from '@src/monsters/grimoire';
import { Creature, CustomMonsterAbility } from '@src/character_sheet/creature';
import { getWeaponMultByRank } from '@src/abilities/combat_styles';
import { BARRIER_COOLDOWN, BRIEF_COOLDOWN, CONDITION_CRIT } from '@src/abilities/constants';

export function addMonstersFromUi(grimoire: Grimoire) {

  // --- Individual Monsters ---

  grimoire.addMonster('TestMonster', (creature: Creature) => {
    creature.setRequiredProperties({
        "alignment": "lawful evil",
        "base_class": "warrior",
        "elite": true,
        "creature_origin": "natural",
        "creature_type": "humanoid",
        "size": "medium",
        "level": 5
      });
    creature.setBaseAttributes([2,3,1,-1,0,-2]);
    creature.setTrainedSkills(["stealth","jump"]);
    creature.setKnowledgeResults({
        "easy": "Easy text",
        "normal": "Normal text"
      });
    creature.addTrait("quadrupedal");
    creature.addCustomSense("Darkvision (60 ft.)");
    creature.addCustomMovementSpeed("Fly 40 ft.");
    creature.addImmunity("Fire");
    creature.addResistant("Cold");
    creature.addVulnerability("Acid");
    creature.setEquippedArmorName({ bodyArmor: "breastplate" });
    creature.setProperties({"has_art":true});
    // --- Begin freeform code ---
    // struct test dummy
    // --- End freeform code ---
  });

}