import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface MonsterRequiredProperties {
  alignment: string;
  base_class: string;
  elite: boolean;
  creature_origin: string;
  creature_type: string;
  size: string;
  level: number;
}

export interface MonsterData {
  name: string;
  requiredProperties: MonsterRequiredProperties;
  freeformCode: string;
  baseAttributes?: [number, number, number, number, number, number];
  trainedSkills?: string[];
  knowledge?: {
    easy?: string;
    normal?: string;
    hard?: string;
    legendary?: string;
  };
  traits?: string[];
  customSenses?: string[];
  customMovementSpeeds?: string[];
  immunities?: string[];
  resistances?: string[];
  vulnerabilities?: string[];
  equippedArmor?: string;
  properties?: Record<string, any>;
}

export interface MonsterGroupKnowledge {
  normal?: string;
  hard?: string;
  legendary?: string;
}

export interface MonsterGroupData {
  name: string;
  knowledge?: MonsterGroupKnowledge;
  description?: string;
  hasArt: boolean;
  sharedFreeformCode: string;
  monsters: MonsterData[];
}

export interface DatabaseData {
  monsters: MonsterData[];
  monsterGroups: MonsterGroupData[];
}

/**
 * Generates the TypeScript initialization body for a single monster.
 * Design Decision:
 * 1. Required properties (alignment, level, origin, type, etc.) are applied first.
 * 2. Structured inputs (attributes, skills, knowledge, traits, defenses, equipment, etc.)
 *    are output next using their corresponding Creature builder methods.
 * 3. The freeform code block is appended last. This guarantees that custom/manual scripts 
 *    in the escape hatch can override or extend any automated properties generated by the UI.
 * 4. Strings that might contain single quotes (like custom senses or defenses) are escaped 
 *    using `.replace(/'/g, "\\'")` to prevent syntax/parsing errors in the generated TypeScript output.
 */
function generateMonsterBody(monster: MonsterData, indent: string): string {
  const lines: string[] = [];

  const reqPropsStr = JSON.stringify(monster.requiredProperties, null, 2)
    .split('\n')
    .map((line, idx) => (idx === 0 ? line : indent + '  ' + line))
    .join('\n');
  lines.push(`${indent}creature.setRequiredProperties(${reqPropsStr});`);

  if (monster.baseAttributes && monster.baseAttributes.length === 6) {
    lines.push(`${indent}creature.setBaseAttributes(${JSON.stringify(monster.baseAttributes)});`);
  }

  if (monster.trainedSkills && monster.trainedSkills.length > 0) {
    lines.push(`${indent}creature.setTrainedSkills(${JSON.stringify(monster.trainedSkills)});`);
  }

  if (monster.knowledge && Object.values(monster.knowledge).some((v) => v)) {
    const cleanKnowledge: Record<string, string> = {};
    for (const [key, value] of Object.entries(monster.knowledge)) {
      if (value) cleanKnowledge[key] = value;
    }
    if (Object.keys(cleanKnowledge).length > 0) {
      const knStr = JSON.stringify(cleanKnowledge, null, 2)
        .split('\n')
        .map((line, idx) => (idx === 0 ? line : indent + '  ' + line))
        .join('\n');
      lines.push(`${indent}creature.setKnowledgeResults(${knStr});`);
    }
  }

  if (monster.traits && monster.traits.length > 0) {
    for (const trait of monster.traits) {
      lines.push(`${indent}creature.addTrait('${trait}');`);
    }
  }

  if (monster.customSenses && monster.customSenses.length > 0) {
    for (const sense of monster.customSenses) {
      lines.push(`${indent}creature.addCustomSense('${sense.replace(/'/g, "\\'")}');`);
    }
  }

  if (monster.customMovementSpeeds && monster.customMovementSpeeds.length > 0) {
    for (const speed of monster.customMovementSpeeds) {
      lines.push(`${indent}creature.addCustomMovementSpeed('${speed.replace(/'/g, "\\'")}');`);
    }
  }

  if (monster.immunities && monster.immunities.length > 0) {
    for (const immunity of monster.immunities) {
      lines.push(`${indent}creature.addImmunity('${immunity.replace(/'/g, "\\'")}');`);
    }
  }

  if (monster.resistances && monster.resistances.length > 0) {
    for (const resistance of monster.resistances) {
      lines.push(`${indent}creature.addResistant('${resistance.replace(/'/g, "\\'")}');`);
    }
  }

  if (monster.vulnerabilities && monster.vulnerabilities.length > 0) {
    for (const vulnerability of monster.vulnerabilities) {
      lines.push(`${indent}creature.addVulnerability('${vulnerability.replace(/'/g, "\\'")}');`);
    }
  }

  if (monster.equippedArmor) {
    lines.push(
      `${indent}creature.setEquippedArmorName({ bodyArmor: '${monster.equippedArmor}' });`,
    );
  }

  if (monster.properties && Object.keys(monster.properties).length > 0) {
    lines.push(`${indent}creature.setProperties(${JSON.stringify(monster.properties)});`);
  }

  lines.push(`${indent}// --- Begin freeform code ---`);
  if (monster.freeformCode) {
    const freeformLines = monster.freeformCode.split('\n');
    for (const line of freeformLines) {
      lines.push(line ? `${indent}${line}` : '');
    }
  }
  lines.push(`${indent}// --- End freeform code ---`);

  return lines.join('\n');
}

export function generateTypeScriptCode(db: DatabaseData): string {
  const parts: string[] = [];

  // Imports header
  parts.push(`// AUTO-GENERATED by monster_ui. Do not edit manually.
// Source: Rise/typescript/monster_ui/monsters_from_ui.json

import { Grimoire } from '@src/monsters/grimoire';
import { Creature, CustomMonsterAbility } from '@src/character_sheet/creature';
import { getWeaponMultByRank } from '@src/abilities/combat_styles';
import { BARRIER_COOLDOWN, BRIEF_COOLDOWN, CONDITION_CRIT } from '@src/abilities/constants';

export function addMonstersFromUi(grimoire: Grimoire) {`);

  // Individual Monsters
  if (db.monsters && db.monsters.length > 0) {
    parts.push(`  // --- Individual Monsters ---`);
    for (const monster of db.monsters) {
      const bodyCode = generateMonsterBody(monster, '    ');
      parts.push(`  grimoire.addMonster('${monster.name}', (creature: Creature) => {
${bodyCode}
  });`);
    }
  }

  // Monster Groups
  if (db.monsterGroups && db.monsterGroups.length > 0) {
    parts.push(`  // --- Monster Groups ---`);
    for (const group of db.monsterGroups) {
      const groupConfigParts: string[] = [];
      groupConfigParts.push(`name: '${group.name}'`);
      if (group.knowledge) {
        groupConfigParts.push(
          `knowledge: ${JSON.stringify(group.knowledge, null, 8).replace(/\n/g, '\n      ')}`,
        );
      }
      if (group.description) {
        groupConfigParts.push(`description: ${JSON.stringify(group.description)}`);
      }
      groupConfigParts.push(`hasArt: ${Boolean(group.hasArt)}`);
      groupConfigParts.push(`sharedInitializer: (creature: Creature) => {
        // --- Begin shared freeform code ---
        ${group.sharedFreeformCode || ''}
        // --- End shared freeform code ---
      }`);

      const configStr = `{\n      ${groupConfigParts.join(',\n      ')}\n    }`;

      const monstersListStr = group.monsters
        .map((monster) => {
          const bodyCode = generateMonsterBody(monster, '          ');
          return `[
        '${monster.name}',
        (creature: Creature) => {
${bodyCode}
        },
      ]`;
        })
        .join(',\n      ');

      parts.push(`  grimoire.addMonsterGroup(
    ${configStr},
    [
      ${monstersListStr}
    ]
  );`);
    }
  }

  parts.push(`}`);
  return parts.join('\n\n');
}

export function saveTypeScriptFile(db: DatabaseData) {
  const tsCode = generateTypeScriptCode(db);
  const targetPath = path.resolve(
    __dirname,
    '../../src/monsters/individual_monsters/monsters_from_ui.ts',
  );

  // Ensure the parent directory exists
  const parentDir = path.dirname(targetPath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  fs.writeFileSync(targetPath, tsCode, 'utf8');
}
