import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface MonsterRequiredProperties {
  alignment: string;
  base_class: string;
  elite: boolean;
  creature_origin: string;
  creature_type: string;
  size: string;
  level: number;
}

export interface MonsterData {
  name: string;
  requiredProperties: MonsterRequiredProperties;
  freeformCode: string;
}

export interface MonsterGroupKnowledge {
  normal?: string;
  hard?: string;
  legendary?: string;
}

export interface MonsterGroupData {
  name: string;
  knowledge?: MonsterGroupKnowledge;
  description?: string;
  hasArt: boolean;
  sharedFreeformCode: string;
  monsters: MonsterData[];
}

export interface DatabaseData {
  monsters: MonsterData[];
  monsterGroups: MonsterGroupData[];
}

export function generateTypeScriptCode(db: DatabaseData): string {
  const parts: string[] = [];

  // Imports header
  parts.push(`// AUTO-GENERATED by monster_ui. Do not edit manually.
// Source: Rise/typescript/monster_ui/monsters_from_ui.json

import { Grimoire } from '@src/monsters/grimoire';
import { Creature, CustomMonsterAbility } from '@src/character_sheet/creature';
import { getWeaponMultByRank } from '@src/abilities/combat_styles';
import { BARRIER_COOLDOWN, BRIEF_COOLDOWN, CONDITION_CRIT } from '@src/abilities/constants';

export function addMonstersFromUi(grimoire: Grimoire) {`);

  // Individual Monsters
  if (db.monsters && db.monsters.length > 0) {
    parts.push(`  // --- Individual Monsters ---`);
    for (const monster of db.monsters) {
      const reqPropsStr = JSON.stringify(monster.requiredProperties, null, 6).replace(
        /\n/g,
        '\n    ',
      ); // indent correctly

      parts.push(`  grimoire.addMonster('${monster.name}', (creature: Creature) => {
    creature.setRequiredProperties(${reqPropsStr});
    // --- Begin freeform code ---
    ${monster.freeformCode || ''}
    // --- End freeform code ---
  });`);
    }
  }

  // Monster Groups
  if (db.monsterGroups && db.monsterGroups.length > 0) {
    parts.push(`  // --- Monster Groups ---`);
    for (const group of db.monsterGroups) {
      const groupConfigParts: string[] = [];
      groupConfigParts.push(`name: '${group.name}'`);
      if (group.knowledge) {
        groupConfigParts.push(
          `knowledge: ${JSON.stringify(group.knowledge, null, 8).replace(/\n/g, '\n      ')}`,
        );
      }
      if (group.description) {
        groupConfigParts.push(`description: ${JSON.stringify(group.description)}`);
      }
      groupConfigParts.push(`hasArt: ${Boolean(group.hasArt)}`);
      groupConfigParts.push(`sharedInitializer: (creature: Creature) => {
        // --- Begin shared freeform code ---
        ${group.sharedFreeformCode || ''}
        // --- End shared freeform code ---
      }`);

      const configStr = `{\n      ${groupConfigParts.join(',\n      ')}\n    }`;

      const monstersListStr = group.monsters
        .map((monster) => {
          const reqPropsStr = JSON.stringify(monster.requiredProperties, null, 10).replace(
            /\n/g,
            '\n          ',
          );
          return `[
        '${monster.name}',
        (creature: Creature) => {
          creature.setRequiredProperties(${reqPropsStr});
          // --- Begin freeform code ---
          ${monster.freeformCode || ''}
          // --- End freeform code ---
        },
      ]`;
        })
        .join(',\n      ');

      parts.push(`  grimoire.addMonsterGroup(
    ${configStr},
    [
      ${monstersListStr}
    ]
  );`);
    }
  }

  parts.push(`}`);
  return parts.join('\n\n');
}

export function saveTypeScriptFile(db: DatabaseData) {
  const tsCode = generateTypeScriptCode(db);
  const targetPath = path.resolve(
    __dirname,
    '../../src/monsters/individual_monsters/monsters_from_ui.ts',
  );

  // Ensure the parent directory exists
  const parentDir = path.dirname(targetPath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  fs.writeFileSync(targetPath, tsCode, 'utf8');
}
