valid_tags = set([
    'Acid',
    'Air',
    'Attune',
    'Attune (shared)',
    'Auditory',
    'Cold',
    'Compulsion',
    'Creation',
    'Curse',
    'Death',
    'Emotion',
    'Detection',
    'Earth',
    'Electricity',
    'Enhancement',
    'Figment',
    'Fire',
    'Flesh',
    'Glamer',
    'Imbuement',
    'Life',
    'Light',
    'Manifestation',
    'Mind',
    'Physical',
    'Planar',
    'Poison',
    'Scrying',
    'Shaping',
    'Shielding',
    'Sizing',
    'Speech',
    'Subtle',
    'Sustain (standard)',
    'Sustain (minor)',
    'Telekinesis',
    'Teleportation',
    'Temporal',
    'Thaumaturgy',
    'Trap',
    'Visual',
    'Water',
])

def is_valid_tag(tag):
    return tag in valid_tags
